<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>cn.luis.coca</groupId>
        <artifactId>coca-boot-dependencies</artifactId>
        <version>2.6.13</version>
        <relativePath>../coca-boot-dependencies/pom.xml</relativePath>
    </parent>

    <artifactId>coca-boot-parent</artifactId>
    <!--主pom版本号-->
    <version>2.6.13</version>

    <packaging>pom</packaging>

    <properties>
        <!--与主pom版本号一致-->
        <coca-children-version>2.6.13</coca-children-version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>cn.luis.coca</groupId>
                <artifactId>coca-boot-core</artifactId>
                <version>${coca-children-version}</version>
            </dependency>
            <dependency>
                <groupId>cn.luis.coca</groupId>
                <artifactId>coca-boot-jackson</artifactId>
                <version>${coca-children-version}</version>
            </dependency>
            <dependency>
                <groupId>cn.luis.coca</groupId>
                <artifactId>coca-boot-log</artifactId>
                <version>${coca-children-version}</version>
            </dependency>
            <dependency>
                <groupId>cn.luis.coca</groupId>
                <artifactId>coca-boot-util</artifactId>
                <version>${coca-children-version}</version>
            </dependency>
            <dependency>
                <groupId>cn.luis.coca</groupId>
                <artifactId>coca-boot-starter-dubbo-nacos</artifactId>
                <version>${coca-children-version}</version>
            </dependency>
            <dependency>
                <groupId>cn.luis.coca</groupId>
                <artifactId>coca-boot-starter-oss</artifactId>
                <version>${coca-children-version}</version>
            </dependency>
            <dependency>
                <groupId>cn.luis.coca</groupId>
                <artifactId>coca-boot-starter-data-db</artifactId>
                <version>${coca-children-version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>